### ISSUE TITLE
When 2 desactivated sites are next to each other, the space between them isn't the same as other sites

### ISSUE THREAD

**Issue by TheNain38** [HelloZeroNet/ZeroHello#2]
![notaligned](https://cloud.githubusercontent.com/assets/13149763/10777222/478e1f42-7d19-11e5-9a41-f50af331f2d2.PNG)

**Comment by HelloZeroNet** [comment]
fixed: https://github.com/HelloZeroNet/ZeroHello/commit/9be49f6bafabf4ced748cee13701cbbea009f838

**Comment by TheNain38** [comment]
@HelloZeroNet It is not fixed:
![bug alignement](https://cloud.githubusercontent.com/assets/13149763/10834520/4587d882-7e9a-11e5-9a2c-b912c8c33200.PNG)

**Comment by HelloZeroNet** [comment]
maybe now

**Comment by TheNain38** [comment]
There is still a little misalignement:
![misalignement](https://cloud.githubusercontent.com/assets/13149763/10836379/383bb690-7ead-11e5-9089-40e3edef62ea.PNG)
